In [1]:
%pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in c:\users\alejandro\onedrive\attachments\lib\site-packages (1.4.7)
Collecting psycopg2-binary
  Downloading psycopg2-binary-2.9.10.tar.gz (385 kB)
  Downloading psycopg2_binary-2.9.9-cp38-cp38-win_amd64.whl (1.2 MB)
Requirement already satisfied: pandas in c:\users\alejandro\onedrive\attachments\lib\site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\alejandro\onedrive\attachments\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\alejandro\onedrive\attachments\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\alejandro\onedrive\attachments\lib\site-packages (from pandas) (1.24.3)Note: you may need to restart the kernel to use updated packages.

    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\Alejandro\OneDrive\Attachments\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Alejandro\\AppData\\Local\\Temp\\pip-install-5thv2zt0\\psycopg2-binary_fe1a06a388a5441e8e746cb9f80ff4ed\\setup.py'"'"'; __file__='"'"'C:\\Users\\Alejandro\\AppData\\Local\\Temp\\pip-install-5thv2zt0\\psycopg2-binary_fe1a06a388a5441e8e746cb9f80ff4ed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk'
         cwd: C:\Users\Alejandro\AppData\Local\Temp\pip-install-5thv2zt0\psycopg2-binary_fe1a06a388a5441e8e746cb9f80ff4ed\
    Complete output (23 lines):
    running egg_info
    creating C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk\psycopg2_binary.egg-info
    writing C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk\psycopg2_binary.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk\psycopg2_binary.egg-info\dependency_links.txt
    writing top-level names to C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk\psycopg2_binary.egg-info\top_level.txt
    writing manifest file 'C:\Users\Alejandro\AppData\Local\Temp\pip-pip-egg-info-0eytwtwk\psycopg2_binary.egg-info\SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cb/0e/bdc8274dc0585090b4e3432267d7be4dfbfd8971c0fa59167c711105a6bf/psycopg2-binary-2.9.10.tar.gz#sha256=4b3df0e6990aa98acda57d983942eff13d824135fe2250e6522edaa782a06de2 (from https://pypi.org/simple/psycopg2-binary/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Requirement already satisfied: six>=1.5 in c:\users\alejandro\onedrive\attachments\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\alejandro\onedrive\attachments\lib\site-packages (from sqlalchemy) (1.0.0)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.9

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres.bexpiibywhevfohcgtue:*************.@aws-0-us-west-2.pooler.supabase.com:5432/postgres"

engine = create_engine(DATABASE_URL)

query = """
SELECT *
FROM credit_risk;
"""

df = pd.read_sql(query, engine)

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [8]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [9]:
# Dimensiones del dataset
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

# Valores faltantes por variable
df.isna().sum()

Filas: 32581
Columnas: 12

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [10]:
# Dimensiones del dataset
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

# Valores faltantes por variable
df.isna().sum()

Filas: 32581
Columnas: 12

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [11]:
# Resumen estadístico de variables numéricas
df.describe().T

,count,mean,std,min,25%,50%,75%,max
person_age,32581.0,27.734600,6.348078,20.00,23.00,26.00,30.00,144.00
person_income,32581.0,66074.848470,61983.119168,4000.00,38500.00,55000.00,79200.00,6000000.00
person_emp_length,31686.0,4.789686,4.142630,0.00,2.00,4.00,7.00,123.00
loan_amnt,32581.0,9589.371106,6322.086646,500.00,5000.00,8000.00,12200.00,35000.00
loan_int_rate,29465.0,11.011695,3.240459,5.42,7.90,10.99,13.47,23.22
loan_status,32581.0,0.218164,0.413006,0.00,0.00,0.00,0.00,1.00
loan_percent_income,32581.0,0.170203,0.106782,0.00,0.09,0.15,0.23,0.83
cb_person_cred_hist_length,32581.0,5.804211,4.055001,2.00,3.00,4.00,8.00,30.00

In [12]:
# Buscar registros duplicados
print("Duplicados:", df.duplicated().sum())

Duplicados: 165

In [13]:
df.sort_values("person_age", ascending=False)[
    ["person_age", "person_emp_length", "person_income"]
].head(10)

       person_age  person_emp_length  person_income
81            144                4.0         250000
32297         144               12.0        6000000
183           144                4.0         200000
747           123                7.0          78000
575           123                2.0          80004
32416          94                1.0          24000
32506          84                2.0          94800
32422          80                7.0          64000
32355          78               41.0          48000
32534          76               23.0          75000

In [14]:
df.sort_values("person_emp_length", ascending=False)[
    ["person_age", "person_emp_length", "person_income"]
].head(10)

       person_age  person_emp_length  person_income
0              22              123.0          59000
210            21              123.0         192000
32355          78               41.0          48000
32515          53               38.0         106000
32428          58               34.0          49000
31866          47               31.0         178000
32263          46               31.0         180000
31867          46               31.0         180000
30914          48               31.0          70000
32562          61               30.0         160000

In [15]:
df_clean = df.copy()

# Eliminar duplicados exactos
df_clean = df_clean.drop_duplicates()

# Eliminar edades claramente imposibles
df_clean = df_clean[df_clean["person_age"] <= 100]

In [17]:
# Eliminar antigüedades laborales imposibles
df_clean = df_clean[
    (df_clean["person_emp_length"].isna()) |
    (df_clean["person_emp_length"] <= df_clean["person_age"])
]

In [18]:
# Eliminar antigüedades laborales imposibles
df_clean = df_clean[
    (df_clean["person_emp_length"].isna()) |
    (df_clean["person_emp_length"] <= df_clean["person_age"])
]

In [19]:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
person_age,32409.0,27.730754,6.210445,20.00,23.00,26.00,30.00,94.00
person_income,32409.0,65894.277053,52517.869973,4000.00,38500.00,55000.00,79200.00,2039784.00
person_emp_length,31522.0,4.782850,4.037343,0.00,2.00,4.00,7.00,41.00
loan_amnt,32409.0,9592.486655,6320.885127,500.00,5000.00,8000.00,12250.00,35000.00
loan_int_rate,29315.0,11.017099,3.241718,5.42,7.90,10.99,13.47,23.22
loan_status,32409.0,0.218705,0.413374,0.00,0.00,0.00,0.00,1.00
loan_percent_income,32409.0,0.170248,0.106785,0.00,0.09,0.15,0.23,0.83
cb_person_cred_hist_length,32409.0,5.811194,4.057899,2.00,3.00,4.00,8.00,30.00

In [20]:
df_clean.to_csv("credit_risk_clean.csv", index=False)

In [21]:
# Para poder encontrar la ruta exacta para encontrar el archivo credit_risk_clean.csv y seguir con el Pipeline en POWER BI.

import os

print(os.getcwd())
print(os.path.abspath("credit_risk_clean.csv"))

c:\Users\Alejandro\Desktop\ranking-amateur-tenis\src\app
c:\Users\Alejandro\Desktop\ranking-amateur-tenis\src\app\credit_risk_clean.csv